service: alexa-hanuman-chalisa

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  stage: ${opt:stage}
  
package:
  artifact: build/distributions/alexa-hanuman-chalisa.zip

functions:
  stories:
    handler: com.varun.alexa.hanumanchalisa.handler.HanumanChalisaStreamHandler
    events:
      - alexaSkill: amzn1.ask.skill.b9521883-f5c6-480e-8d26-eb044c4edfab